"""Add description columns to tags and categories

Revision ID: 982371e0f5aa
Revises: 
Create Date: 2025-09-23 21:28:08.296205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982371e0f5aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###