{
 "title": "k6 Prometheus (simplified)",
 "description": "Visualize k6 OSS results stored in Prometheus",
 "tags": [
  "prometheus",
  "k6"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "adhoc_filter", "label": "AdhocFilter" },
   {
    "name": "testid",
    "label": "Test ID",
    "query": "label_values(k6_http_reqs, testid)"
   }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(rate(k6_http_reqs[1m]))" }
   ]
  },
  {
   "title": "Errores %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "100 * (sum(rate(k6_http_req_failed[1m])) / clamp_min(sum(rate(k6_http_reqs[1m])), 1))"
    }
   ]
  },
  {
   "title": "Latencia (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 6 },
   "targets": [
    { "expr": "avg(k6_http_req_duration)" }
   ]
  },
  {
   "title": "Latencia (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "quantile_over_time(0.95, k6_http_req_duration[$__interval])"
    }
   ]
  },
  {
   "title": "Latencia por testid (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "avg by (testid) (k6_http_req_duration{testid=~\"$testid\"})",
     "legendFormat": "{{testid}}"
    }
   ]
  }
 ]
}