// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto/metadata/metadata.proto

package metadata

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataService_EnrichTrack_FullMethodName       = "/metadata.MetadataService/EnrichTrack"
	MetadataService_BatchEnrichTracks_FullMethodName = "/metadata.MetadataService/BatchEnrichTracks"
	MetadataService_SearchTracks_FullMethodName      = "/metadata.MetadataService/SearchTracks"
)

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MetadataService provides music metadata enrichment
type MetadataServiceClient interface {
	// EnrichTrack enriches a single track with metadata from external sources
	EnrichTrack(ctx context.Context, in *EnrichTrackRequest, opts ...grpc.CallOption) (*EnrichTrackResponse, error)
	// BatchEnrichTracks enriches multiple tracks in a single request
	BatchEnrichTracks(ctx context.Context, in *BatchEnrichRequest, opts ...grpc.CallOption) (*BatchEnrichResponse, error)
	// SearchTracks searches for tracks by various criteria
	SearchTracks(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type metadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataServiceClient(cc grpc.ClientConnInterface) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) EnrichTrack(ctx context.Context, in *EnrichTrackRequest, opts ...grpc.CallOption) (*EnrichTrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichTrackResponse)
	err := c.cc.Invoke(ctx, MetadataService_EnrichTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) BatchEnrichTracks(ctx context.Context, in *BatchEnrichRequest, opts ...grpc.CallOption) (*BatchEnrichResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchEnrichResponse)
	err := c.cc.Invoke(ctx, MetadataService_BatchEnrichTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) SearchTracks(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, MetadataService_SearchTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
// All implementations must embed UnimplementedMetadataServiceServer
// for forward compatibility.
//
// MetadataService provides music metadata enrichment
type MetadataServiceServer interface {
	// EnrichTrack enriches a single track with metadata from external sources
	EnrichTrack(context.Context, *EnrichTrackRequest) (*EnrichTrackResponse, error)
	// BatchEnrichTracks enriches multiple tracks in a single request
	BatchEnrichTracks(context.Context, *BatchEnrichRequest) (*BatchEnrichResponse, error)
	// SearchTracks searches for tracks by various criteria
	SearchTracks(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedMetadataServiceServer()
}

// UnimplementedMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataServiceServer struct{}

func (UnimplementedMetadataServiceServer) EnrichTrack(context.Context, *EnrichTrackRequest) (*EnrichTrackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnrichTrack not implemented")
}
func (UnimplementedMetadataServiceServer) BatchEnrichTracks(context.Context, *BatchEnrichRequest) (*BatchEnrichResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchEnrichTracks not implemented")
}
func (UnimplementedMetadataServiceServer) SearchTracks(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchTracks not implemented")
}
func (UnimplementedMetadataServiceServer) mustEmbedUnimplementedMetadataServiceServer() {}
func (UnimplementedMetadataServiceServer) testEmbeddedByValue()                         {}

// UnsafeMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataServiceServer will
// result in compilation errors.
type UnsafeMetadataServiceServer interface {
	mustEmbedUnimplementedMetadataServiceServer()
}

func RegisterMetadataServiceServer(s grpc.ServiceRegistrar, srv MetadataServiceServer) {
	// If the following call pancis, it indicates UnimplementedMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataService_ServiceDesc, srv)
}

func _MetadataService_EnrichTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).EnrichTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_EnrichTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).EnrichTrack(ctx, req.(*EnrichTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_BatchEnrichTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchEnrichRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).BatchEnrichTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_BatchEnrichTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).BatchEnrichTracks(ctx, req.(*BatchEnrichRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_SearchTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).SearchTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_SearchTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).SearchTracks(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataService_ServiceDesc is the grpc.ServiceDesc for MetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metadata.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnrichTrack",
			Handler:    _MetadataService_EnrichTrack_Handler,
		},
		{
			MethodName: "BatchEnrichTracks",
			Handler:    _MetadataService_BatchEnrichTracks_Handler,
		},
		{
			MethodName: "SearchTracks",
			Handler:    _MetadataService_SearchTracks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/metadata/metadata.proto",
}
