// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/metadata/metadata.proto

package metadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for enriching a single track
type EnrichTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,2,opt,name=artist,proto3" json:"artist,omitempty"`
	Album         string                 `protobuf:"bytes,3,opt,name=album,proto3" json:"album,omitempty"`
	Duration      int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	GenreHint     string                 `protobuf:"bytes,5,opt,name=genre_hint,json=genreHint,proto3" json:"genre_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichTrackRequest) Reset() {
	*x = EnrichTrackRequest{}
	mi := &file_proto_metadata_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichTrackRequest) ProtoMessage() {}

func (x *EnrichTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichTrackRequest.ProtoReflect.Descriptor instead.
func (*EnrichTrackRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadata_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *EnrichTrackRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EnrichTrackRequest) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *EnrichTrackRequest) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *EnrichTrackRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *EnrichTrackRequest) GetGenreHint() string {
	if x != nil {
		return x.GenreHint
	}
	return ""
}

// Response message for track enrichment
type EnrichTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Metadata      *SpotifyMetadata       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Confidence    float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"` // NUEVO: confianza del match
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichTrackResponse) Reset() {
	*x = EnrichTrackResponse{}
	mi := &file_proto_metadata_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichTrackResponse) ProtoMessage() {}

func (x *EnrichTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichTrackResponse.ProtoReflect.Descriptor instead.
func (*EnrichTrackResponse) Descriptor() ([]byte, []int) {
	return file_proto_metadata_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *EnrichTrackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnrichTrackResponse) GetMetadata() *SpotifyMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EnrichTrackResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *EnrichTrackResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// Request message for batch enrichment
type BatchEnrichRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*EnrichTrackRequest  `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEnrichRequest) Reset() {
	*x = BatchEnrichRequest{}
	mi := &file_proto_metadata_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEnrichRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEnrichRequest) ProtoMessage() {}

func (x *BatchEnrichRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEnrichRequest.ProtoReflect.Descriptor instead.
func (*BatchEnrichRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadata_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *BatchEnrichRequest) GetTracks() []*EnrichTrackRequest {
	if x != nil {
		return x.Tracks
	}
	return nil
}

// Response message for batch enrichment
type BatchEnrichResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*EnrichTrackResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEnrichResponse) Reset() {
	*x = BatchEnrichResponse{}
	mi := &file_proto_metadata_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEnrichResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEnrichResponse) ProtoMessage() {}

func (x *BatchEnrichResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEnrichResponse.ProtoReflect.Descriptor instead.
func (*BatchEnrichResponse) Descriptor() ([]byte, []int) {
	return file_proto_metadata_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *BatchEnrichResponse) GetResults() []*EnrichTrackResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

// Search request message
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_metadata_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadata_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Search response message
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*SpotifyMetadata     `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	TotalResults  int32                  `protobuf:"varint,2,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_metadata_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_metadata_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResponse) GetTracks() []*SpotifyMetadata {
	if x != nil {
		return x.Tracks
	}
	return nil
}

func (x *SearchResponse) GetTotalResults() int32 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

// Spotify metadata structure
type SpotifyMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpotifyId     string                 `protobuf:"bytes,1,opt,name=spotify_id,json=spotifyId,proto3" json:"spotify_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Album         string                 `protobuf:"bytes,4,opt,name=album,proto3" json:"album,omitempty"`
	Genres        []string               `protobuf:"bytes,5,rep,name=genres,proto3" json:"genres,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,6,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	AlbumArtUrl   string                 `protobuf:"bytes,7,opt,name=album_art_url,json=albumArtUrl,proto3" json:"album_art_url,omitempty"`
	PreviewUrl    string                 `protobuf:"bytes,8,opt,name=preview_url,json=previewUrl,proto3" json:"preview_url,omitempty"`
	DurationMs    int32                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Popularity    float32                `protobuf:"fixed32,10,opt,name=popularity,proto3" json:"popularity,omitempty"`
	Confidence    float32                `protobuf:"fixed32,11,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ExternalUrl   string                 `protobuf:"bytes,12,opt,name=external_url,json=externalUrl,proto3" json:"external_url,omitempty"`
	Artists       []string               `protobuf:"bytes,13,rep,name=artists,proto3" json:"artists,omitempty"`                             // NUEVO: para colaboraciones
	AlbumType     string                 `protobuf:"bytes,14,opt,name=album_type,json=albumType,proto3" json:"album_type,omitempty"`        // NUEVO: single, album, compilation
	TrackNumber   int32                  `protobuf:"varint,15,opt,name=track_number,json=trackNumber,proto3" json:"track_number,omitempty"` // NUEVO
	DiscNumber    int32                  `protobuf:"varint,16,opt,name=disc_number,json=discNumber,proto3" json:"disc_number,omitempty"`    // NUEVO
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpotifyMetadata) Reset() {
	*x = SpotifyMetadata{}
	mi := &file_proto_metadata_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpotifyMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotifyMetadata) ProtoMessage() {}

func (x *SpotifyMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotifyMetadata.ProtoReflect.Descriptor instead.
func (*SpotifyMetadata) Descriptor() ([]byte, []int) {
	return file_proto_metadata_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *SpotifyMetadata) GetSpotifyId() string {
	if x != nil {
		return x.SpotifyId
	}
	return ""
}

func (x *SpotifyMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SpotifyMetadata) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *SpotifyMetadata) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *SpotifyMetadata) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *SpotifyMetadata) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *SpotifyMetadata) GetAlbumArtUrl() string {
	if x != nil {
		return x.AlbumArtUrl
	}
	return ""
}

func (x *SpotifyMetadata) GetPreviewUrl() string {
	if x != nil {
		return x.PreviewUrl
	}
	return ""
}

func (x *SpotifyMetadata) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *SpotifyMetadata) GetPopularity() float32 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *SpotifyMetadata) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SpotifyMetadata) GetExternalUrl() string {
	if x != nil {
		return x.ExternalUrl
	}
	return ""
}

func (x *SpotifyMetadata) GetArtists() []string {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *SpotifyMetadata) GetAlbumType() string {
	if x != nil {
		return x.AlbumType
	}
	return ""
}

func (x *SpotifyMetadata) GetTrackNumber() int32 {
	if x != nil {
		return x.TrackNumber
	}
	return 0
}

func (x *SpotifyMetadata) GetDiscNumber() int32 {
	if x != nil {
		return x.DiscNumber
	}
	return 0
}

var File_proto_metadata_metadata_proto protoreflect.FileDescriptor

const file_proto_metadata_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/metadata/metadata.proto\x12\bmetadata\"\x93\x01\n" +
	"\x12EnrichTrackRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x02 \x01(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\x03 \x01(\tR\x05album\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\x12\x1d\n" +
	"\n" +
	"genre_hint\x18\x05 \x01(\tR\tgenreHint\"\xab\x01\n" +
	"\x13EnrichTrackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x125\n" +
	"\bmetadata\x18\x02 \x01(\v2\x19.metadata.SpotifyMetadataR\bmetadata\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\"J\n" +
	"\x12BatchEnrichRequest\x124\n" +
	"\x06tracks\x18\x01 \x03(\v2\x1c.metadata.EnrichTrackRequestR\x06tracks\"N\n" +
	"\x13BatchEnrichResponse\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.metadata.EnrichTrackResponseR\aresults\"S\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"h\n" +
	"\x0eSearchResponse\x121\n" +
	"\x06tracks\x18\x01 \x03(\v2\x19.metadata.SpotifyMetadataR\x06tracks\x12#\n" +
	"\rtotal_results\x18\x02 \x01(\x05R\ftotalResults\"\xf5\x03\n" +
	"\x0fSpotifyMetadata\x12\x1d\n" +
	"\n" +
	"spotify_id\x18\x01 \x01(\tR\tspotifyId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\x04 \x01(\tR\x05album\x12\x16\n" +
	"\x06genres\x18\x05 \x03(\tR\x06genres\x12!\n" +
	"\frelease_date\x18\x06 \x01(\tR\vreleaseDate\x12\"\n" +
	"\ralbum_art_url\x18\a \x01(\tR\valbumArtUrl\x12\x1f\n" +
	"\vpreview_url\x18\b \x01(\tR\n" +
	"previewUrl\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x05R\n" +
	"durationMs\x12\x1e\n" +
	"\n" +
	"popularity\x18\n" +
	" \x01(\x02R\n" +
	"popularity\x12\x1e\n" +
	"\n" +
	"confidence\x18\v \x01(\x02R\n" +
	"confidence\x12!\n" +
	"\fexternal_url\x18\f \x01(\tR\vexternalUrl\x12\x18\n" +
	"\aartists\x18\r \x03(\tR\aartists\x12\x1d\n" +
	"\n" +
	"album_type\x18\x0e \x01(\tR\talbumType\x12!\n" +
	"\ftrack_number\x18\x0f \x01(\x05R\vtrackNumber\x12\x1f\n" +
	"\vdisc_number\x18\x10 \x01(\x05R\n" +
	"discNumber2\xf2\x01\n" +
	"\x0fMetadataService\x12J\n" +
	"\vEnrichTrack\x12\x1c.metadata.EnrichTrackRequest\x1a\x1d.metadata.EnrichTrackResponse\x12P\n" +
	"\x11BatchEnrichTracks\x12\x1c.metadata.BatchEnrichRequest\x1a\x1d.metadata.BatchEnrichResponse\x12A\n" +
	"\fSearchTracks\x12\x17.metadata.SearchRequest\x1a\x18.metadata.SearchResponseB\x1dZ\x1bmusicservice/proto/metadatab\x06proto3"

var (
	file_proto_metadata_metadata_proto_rawDescOnce sync.Once
	file_proto_metadata_metadata_proto_rawDescData []byte
)

func file_proto_metadata_metadata_proto_rawDescGZIP() []byte {
	file_proto_metadata_metadata_proto_rawDescOnce.Do(func() {
		file_proto_metadata_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metadata_metadata_proto_rawDesc), len(file_proto_metadata_metadata_proto_rawDesc)))
	})
	return file_proto_metadata_metadata_proto_rawDescData
}

var file_proto_metadata_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_metadata_metadata_proto_goTypes = []any{
	(*EnrichTrackRequest)(nil),  // 0: metadata.EnrichTrackRequest
	(*EnrichTrackResponse)(nil), // 1: metadata.EnrichTrackResponse
	(*BatchEnrichRequest)(nil),  // 2: metadata.BatchEnrichRequest
	(*BatchEnrichResponse)(nil), // 3: metadata.BatchEnrichResponse
	(*SearchRequest)(nil),       // 4: metadata.SearchRequest
	(*SearchResponse)(nil),      // 5: metadata.SearchResponse
	(*SpotifyMetadata)(nil),     // 6: metadata.SpotifyMetadata
}
var file_proto_metadata_metadata_proto_depIdxs = []int32{
	6, // 0: metadata.EnrichTrackResponse.metadata:type_name -> metadata.SpotifyMetadata
	0, // 1: metadata.BatchEnrichRequest.tracks:type_name -> metadata.EnrichTrackRequest
	1, // 2: metadata.BatchEnrichResponse.results:type_name -> metadata.EnrichTrackResponse
	6, // 3: metadata.SearchResponse.tracks:type_name -> metadata.SpotifyMetadata
	0, // 4: metadata.MetadataService.EnrichTrack:input_type -> metadata.EnrichTrackRequest
	2, // 5: metadata.MetadataService.BatchEnrichTracks:input_type -> metadata.BatchEnrichRequest
	4, // 6: metadata.MetadataService.SearchTracks:input_type -> metadata.SearchRequest
	1, // 7: metadata.MetadataService.EnrichTrack:output_type -> metadata.EnrichTrackResponse
	3, // 8: metadata.MetadataService.BatchEnrichTracks:output_type -> metadata.BatchEnrichResponse
	5, // 9: metadata.MetadataService.SearchTracks:output_type -> metadata.SearchResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_metadata_metadata_proto_init() }
func file_proto_metadata_metadata_proto_init() {
	if File_proto_metadata_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metadata_metadata_proto_rawDesc), len(file_proto_metadata_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metadata_metadata_proto_goTypes,
		DependencyIndexes: file_proto_metadata_metadata_proto_depIdxs,
		MessageInfos:      file_proto_metadata_metadata_proto_msgTypes,
	}.Build()
	File_proto_metadata_metadata_proto = out.File
	file_proto_metadata_metadata_proto_goTypes = nil
	file_proto_metadata_metadata_proto_depIdxs = nil
}
