services:
  web:
    build: ./web
    ports:
    - "3000:3000"
  api:
    build: ./api
    ports:
    - "5000:5000"
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
    - "5432:5432"
  network:
    build: ./networking
    profiles:
    - build-only
    volumes:
    - ./networking/volume:/home/ubuntu