server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: campus
  
  webflux:
    base-path: /api

  r2dbc:
    url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/events_db
    username: ${DB_USERNAME:app}
    password: ${DB_PASSWORD:123}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20

  flyway:
    enabled: true
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/events_db?useSSL=false&allowPublicKeyRetrieval=true
    user: ${DB_USERNAME:app}
    password: ${DB_PASSWORD:123}
    locations: classpath:db/migration

  grpc:
    client:
      channels:
        reco:
          address: ${RECOMMENDATIONS_HOST:localhost}:${RECOMMENDATIONS_PORT:8000}
          enable-keep-alive: true
          keep-alive-time: 30s
          keep-alive-timeout: 10s
          keep-alive-without-calls: true