server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      # Configuración de rutas
      routes:
        # Ruta para servicio de usuarios
        - id: auth-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1  # Remueve /api del path
            - AddRequestHeader=X-Gateway, ApiGateway

        # Ruta para servicio de admin
        - id: admin-dashboard-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/auth_admin/admin/**
          filters:
            - StripPrefix=2  # Remueve /api/auth_admin del path
            - AddRequestHeader=X-Gateway, ApiGateway
        
        # Ruta para servicio de productos
        - id: activities-service
          uri: http://localhost:8002
          predicates:
            - Path=/api/activities/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Gateway, ApiGateway
        
        # Ruta para servicio de órdenes
        - id: gamification-service
          uri: http://localhost:8003
          predicates:
            - Path=/api/gamification/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Gateway, ApiGateway

        - id: users-service
          uri: http://localhost:8004
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Gateway, ApiGateway

        - id: admin-users-stats-service
          uri: http://localhost:8004
          predicates:
            - Path=/api/users_admin/admin/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Gateway, ApiGateway
        
        - id: posts-service
          uri: http://localhost:8005
          predicates:
            - Path=/api/posts/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Gateway, ApiGateway

        - id: admin-service
          uri: http://localhost:8006
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Gateway, ApiGateway

# Actuator endpoints para monitoreo
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO