apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script
  
data:
  k6_rate_limit_test.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';
    import { Trend, Counter } from 'k6/metrics';

    export let rejected = new Counter('rejected_429');
    export let reqDuration = new Trend('req_duration_ms');

    export let options = {
      stages: [
        { duration: '30s', target: 20 },   // warmup
        { duration: '2m', target: 100 },   // sustained load
        { duration: '30s', target: 400 },  // spike
        { duration: '1m', target: 0 },     // cooldown
      ],
      thresholds: {
        'http_req_duration': ['p(95)<1000'], // p95 < 1s
        'rejected_429': ['count<1000'],      // example threshold
      },
    };

    function randomIp(seed) {
      // generate pseudo-random IPv4 from vu id + seed
      let a = (seed * 97) % 255;
      let b = (seed * 53) % 255;
      let c = (seed * 23) % 255;
      let d = (seed * 13) % 255;
      return `${a}.${b}.${c}.${d}`;
    }

    export default function () {
      const url = __ENV.TARGET_URL || 'http://api-gateway:8080/api/users/health';

      // create a user and ip per vu
      const vu = __VU;
      const ip = randomIp(vu);
      const headers = {
        'X-Forwarded-For': ip,
        'Accept': 'application/json',
        // If testing authenticated behavior, set Authorization:
        // 'Authorization': `Bearer ${__ENV.TEST_JWT || ''}`
      };

      let res = http.get(url, { headers: headers, tags: { ip: ip } });

      reqDuration.add(res.timings.duration);
      check(res, {
        'status is 200 or 429 or 5xx': (r) => r.status === 200 || r.status === 429 || r.status >= 500,
      });

      if (res.status === 429) {
        rejected.add(1);
      }

      sleep(1);
    }

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k6-results-pvc
  
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-run
  
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: k6
          image: loadimpact/k6:latest
          imagePullPolicy: IfNotPresent
          command: [ "sh", "-c" ]
          args:
            - >
              k6 run /scripts/k6_rate_limit_test.js --out json=/results/results.json;
              echo "k6 exit code: $?" ;
              sleep 2;
          env:
            - name: TARGET_URL
              value: "http://api-gateway.default.svc.cluster.local:8080/api/users" # ajusta
            - name: FAKE_IP
              value: "192.0.2.1"
          volumeMounts:
            - name: script
              mountPath: /scripts
            - name: results
              mountPath: /results
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: script
          configMap:
            name: k6-script
            defaultMode: 0644
        - name: results
          persistentVolumeClaim:
            claimName: k6-results-pvc
