apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-knee-script-influx
  namespace: default
data:
  find_knee.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export const options = {
      insecureSkipTLSVerify: true,
      stages: [
        { duration: '10m', target: 2000 },  
        { duration: '1m', target: 0 },
      ],
    };

    export default function () {
      const url = __ENV.TARGET_URL; 
      
      const params = {
        headers: {
          'X-Forwarded-For': '50.50.50.50',
        },
      };
      
      const res = http.get(url, params);
      check(res, { 'status es 200': (r) => r.status === 200 });
      sleep(0.5);
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-stress-influx
  namespace: default
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: k6
          image: grafana/k6:latest
          env:
            # Configuración para ignorar SSL
            - name: K6_INSECURE_SKIP_TLS_VERIFY
              value: "true"

            # TU OBJETIVO
            - name: TARGET_URL
              value: "https://136.112.28.155/api/users/health"

          command: ["k6"]
          args:
            [
              "run",
              # CAMBIO CLAVE: Salida a InfluxDB en lugar de Prometheus
              "--out", "influxdb=http://influxdb.default.svc.cluster.local:8086/k6",
              "/scripts/find_knee.js"
            ]
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      restartPolicy: Never
      volumes:
        - name: script-volume
          configMap:
            name: k6-knee-script-influx